language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ChainRecursive")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("ChainRecursive")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
